version: "3.7"

services:
  pasarela:
    build: .
    ports:
      - "8090:8090"
  estaciones:
    build: ../alquileres2/
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/estaciones?authSource=admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
  usuarios:
    build: ../UsuariosApi/UsuarioApi/
    ports:
      - "5058:5058"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://root:example@mongo:27017/usuarios?authSource=admin
      - ASPNETCORE_KESTREL__ENDPOINTS__HTTP__URL=http://usuarios:5058
    depends_on:
      - mongo
  alquileres:
    build: ../alquileres/
    ports:
      - "8080:8080"
    environment:
      - DATABASE_CONNECTION_STRING=mysql://root:example@mysql:3306/ARSO
    depends_on:
      - mysql
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ARSO
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  mongo_data:
